services:
  dila-image-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dila-headless-image-editor
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./images:/app/images
      - ./fonts:/app/fonts
    env_file:
      - .env
    environment:
      - DEBUG=False
      - LOG_LEVEL=INFO
      - PORT=5000
      - HOST=0.0.0.0
      - DEFAULT_FONT_FAMILY=Roboto
      - DEFAULT_FONT_SIZE=36
      - CLEANUP_ENABLED=True
      - CLEANUP_INTERVAL=3600
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
  # Development mode
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dila-headless-image-editor-dev
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - PORT=5000
    command: dev
    restart: unless-stopped 